telefonicaid/thinking-cities

docs/authentication_api.md

From issue: https://github.com/telefonicaid/fiware-iot-stack/issues/4

Explain right way to check a token

---

docs/index.md

Clarifying FIWARE vs. no-FIWARE status on some components

---

docs/context_broker.md
docs/data_api.md

* Updating documentation to NGSIv2
* Fixing links
* Adding more stuff (mainly references)

FIX contextbroker & ngsi documentation

---

docs/index.md
docs/multitenancy.md
mkdocs.yml

Same as PR https://github.com/telefonicaid/fiware-iot-stack/pull/16, but in the right branch ;)

ADD multitenancy doc

---

docs/quickguide.md

Ammends for getting started:
- Changed ports and changed protocol in URLs (still remains test.ttcloud.net)
- Removed references to freeboard
- Removed links to former POSTMAN collections
- Some other minor changes

ammends for getting started

---

docs/cep.md
docs/cep_api.md

FIX CEP rigth documentation
REMOVE references to management portal

Fix some CEP stuff, porting same fixes already in release/v4.0 branch

---

docs/device_api.md

ADD Documentation about the JSON Protocol

---

docs/index.md

Change "Data API to CEP API"

---

docs/device_api.md
docs/topics/character_set_limitations.md
docs/topics/data_calculation.md
docs/topics/device_connection.md
docs/topics/geolocalized_entities.md
docs/topics/how_notifications_work.md
docs/topics/modelling_considerations.md
docs/topics/performance_considerations.md
docs/topics/subcriptions_and_registrations.md
mkdocs.yml

Topics added by this PR:
- Character set limitations
- How to send notifications
- Geolocalized entities
- Subscriptions and registrations
- Performance considerations

ADD several documentation topics

---

docs/topics/data_calculation.md

Add doc for CEP section in data calc

---

docs/multitenancy.md
docs/topics/how_notifications_work.md
docs/topics/subcriptions_and_registrations.md

Some little fixes:
* Example in multitenancy section
* Example regarding how TimeInstant is used
* Example for subscriptions and registrations

FIX issues recently raised during a global review

---

docs/data_api.md

ADD srv and subsrv headers to data API examples

---

docs/device_api.md

Add fixes to the IoT Device section.

Update iotam protocol

---

docs/device_api.md

Fixing https://github.com/telefonicaid/fiware-iot-stack/issues/71 and more

Several minor bugfixes

---

postman/ThinkingCities APIs Basic Ops.postman_collection.json

Added new requests:
* Create custom notification
* Create entity update rule
* Get attribute aggregation
The diff shows other changes also, but they seem to be due to slightly different rendering in Postman version newer than the one used to export the original collection file.

ADD new operations in postman collection

---

docs/authentication_api.md
docs/cep_api.md
docs/historicdata_api.md
docs/management_api.md

fix issue  https://github.com/telefonicaid/fiware-iot-stack/issues/77

replace reference to test.ttcloud.net for component_host : component_port

---

postman/README.md
postman/ThinkingCities APIs Basic Ops.postman_collection.json

- Section for CKAN requests added
- IoT Agent requests completed
- Environment variables changed to allow collection to be used for both onpresmise and SaaS environment

CKAN and some IOTA requests added

---

postman/README.md
postman/ThinkingCities APIs Basic Ops.postman_collection.json

Some fixes on the work done by PR #113

FIX postman collection

---

postman/ThinkingCities APIs Basic Ops.postman_collection.json

Added request "Create rule Lamp Alarm HTTP POST"

Added request create rule with action post

---

postman/ThinkingCities APIs Basic Ops.postman_collection.json

- Changes in perseo collection in order to simplify som rules
- Changes in Iota collection

Updates after Vigo session

---

docs/device_api.md

This PR implies usage of iotagent-json 1.13.0+ and iotagent-ul 1.12.0

add protocol to topic

---

docs/data_api.md

Changes:
* Use geo:json in example, instead of geo:point
* Include upsert example

Enhance data API doc

---

postman/ThinkingCities APIs Basic Ops.postman_collection.json

- Added apikey to device provision
- New requests for CEP

Update ThinkingCities APIs Basic Ops.postman_collection.json

---

.readthedocs.yml
docs/requirements.txt

mimics https://github.com/telefonicaid/iotagent-ul/pull/557

Update RTD files

---

.readthedocs.yml
docs/requirements.txt

Align with https://github.com/telefonicaid/fiware-orion/blob/master/.readthedocs.yml and https://github.com/telefonicaid/fiware-orion/blob/master/doc/requirements.txt

FIX .readthedocs.yml

---

docs/css/style.css

Add some other minor fixes to #148 
- Code style
- Nav bar background colours fix
- Add more TEF colours to palette

Add minor css changes

---

docs/device_api.md
docs/topics/device_connection.md
docs/topics/geolocalized_entities.md
docs/topics/how_notifications_work.md
postman/ThinkingCities APIs Basic Ops.postman_collection.json

Replace `services` to `groups` in API requests
